#!/bin/bash
pwd=`pwd`
mkdir -p DEBS/qtnx/DEBIAN
mkdir -p DEBS/qtnx/usr/bin
qmake-qt4
make
cp qtnx DEBS/qtnx/usr/bin/
echo "Package: qtnx
Version: 1.0
Section: base
Priority: optional
Architecture: all
Depends: bash
Maintainer: Hugues CHARBONNIER <hcharbonnier@dotriver.eu>
Description: qtnx
" > DEBS/qtnx/DEBIAN/control
cd DEBS
dpkg --build qtnx
echo "Paquet construit dans le répertoire ./DEBS"
