#!/bin/bash
pwd=`pwd`
mkdir -p DEBS/nxcl/DEBIAN
#./configure --prefix="$pwd/DEBS/nxcl"
make
make install
echo "Package: nxcl
Version: 1.0
Section: base
Priority: optional
Architecture: all
Depends: bash
Maintainer: Hugues CHARBONNIER <hcharbonnier@dotriver.eu>
Description: nxcl
" > DEBS/nxcl/DEBIAN/control
cd DEBS
dpkg --build nxcl
echo "Paquet construit dans le répertoire ./DEBS"
